version: '3'
services:
  db:
    image: postgres:14-alpine
    restart: always
    env_file:
      .env
    ports:
      - ${DB_PORT}:5432
  app:
    build: .
    restart: always
    env_file:
      .env
    ports:
      - 3000:3000
  